### ISSUE TITLE
не работает на 1.16.4

### ISSUE THREAD

**Issue by dimk-o** [dmytrohoi/tg-bridge-pyplugin#1]
Отрабатывают только тестовые команды
на линк и остальное не реагирует

**Comment by dmytrohoi** [comment]
Использование `/link` (и тому подобного) подразумевает что бот будет знать как обрабатывать такую команду.

Реализация такого бота есть тут: [@nurecraft/bot](https://github.com/nurecraft/bot)

**Comment by dimk-o** [comment]
т.е. из коробки плагин умеет только отправлять сообщения через команду /telegram <текст>
и отправлять уведомления "startup_notification" и "shutdown_notification" ?

а для двустороннего чата необходимо ставить что-то дополнительно?
про это в описании нигде не указано

**Comment by dmytrohoi** [comment]
Да, почти. Из коробки доступны нотификации напрямую в Telegram, отправка сообщений в Telegram, зарезервированные команды на сопряжение (/link) и ответ с Telegram в чат игры.

**Comment by dmytrohoi** [comment]
`request to your implemented Telegram Bot.` ([SpigotMC](https://www.spigotmc.org/resources/telegrambridge.83743/)) предполагается что бот у вас уже реализован и работает через RCON с вашим сервером.
